version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3003:3003"
    networks:
      - app-network
    depends_on:
      - streamlitapp

  streamlitapp:
    build:
      context: ./streamlitapp
    ports:
      - "8501:8501"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
