# Use the official Node.js image as a base
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json files to the container
COPY package.json package-lock.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your server listens on
EXPOSE 3003

# Define environment variables (if needed)
# ENV NODE_ENV=production
# ENV STREAMLIT_APP_URL="http://localhost:8501"

# Run the Node.js server
CMD ["node", "server.js"]